spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/food_order
    username: root
    password: 123
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update